# k2hash_rust
#
# Copyright 2025 LY Corporation.
# 
# Rust driver for k2hash that is a NoSQL Key Value Store(KVS) library.
# For k2hash, see https://github.com/yahoojapan/k2hash for the details.
#  
# For the full copyright and license information, please view
# the license file that was distributed with this source code.
#  
# AUTHOR:   Hirotaka Wakabayashi
# CREATE:   Fri, 17 Jul 2025
# REVISION:                        
#  

name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./.github/scripts/install_dependencies.sh
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test --workspace --all-features --all-targets --verbose
      - name: Build docs
        run: cargo doc --no-deps

#
# Local variables:
# tab-width: 4
# c-basic-offset: 4
# End:
# vim600: expandtab sw=4 ts=4 fdm=marker
# vim<600: expandtab sw=4 ts=4
#
