# k2hash_rust
#
# Copyright 2025 LY Corporation.
# 
# Rust driver for k2hash that is a NoSQL Key Value Store(KVS) library.
# For k2hash, see https://github.com/yahoojapan/k2hash for the details.
#  
# For the full copyright and license information, please view
# the license file that was distributed with this source code.
#  
# AUTHOR:   Hirotaka Wakabayashi
# CREATE:   Fri, 17 Jul 2025
# REVISION:                        
#  

name: CI & Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  test:
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: ./.github/scripts/install_dependencies.sh
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
      - run: cargo build --verbose
      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test --workspace --all-features --all-targets --verbose
      - name: Build docs
        run: cargo doc --no-deps

  publish:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token $CARGO_REGISTRY_TOKEN

#
# Local variables:
# tab-width: 4
# c-basic-offset: 4
# End:
# vim600: expandtab sw=4 ts=4 fdm=marker
# vim<600: expandtab sw=4 ts=4
#
